### ISSUE TITLE
excluded? doesn't work with engines?

### ISSUE THREAD

**Issue by amencarini** [svenfuchs/routing-filter#46]
I am unsure if there's something wrong with the way I'm trying to get this done. I'm Ruby 2.0.0-p0, Rails 3.2.13, using Spree 1.3.2

Here's a snippet of my `routes.rb`:

``` ruby
Project::Application.routes.draw do

  filter :locale, exclude: /^\/admin/

  match '/faq' => "faqs#index", as: "faq"
  mount Spree::Core::Engine, at: '/'

end
```

In `locale.rb`, in the `excluded?(url)` method, `url` is always `'/'` for all Spree links. This means that all links of the admin area get the locale prepended even if I have admin excluded via regex.
I could put the filter inside Spree:

``` ruby
Spree::Core::Engine.routes.prepend do
  filter :locale, exclude: /^\/admin/
end
```

But that would prevent me from having routes outside Spree that get the "locale" treatment.

**Comment by jumski** [comment]
`spree_i18n` includes routing-filter by default, ([source](https://github.com/spree-contrib/spree_i18n/blob/master/config/routes.rb#L3)), i've tried multiple things and the definition from spree_i18n is always called after my defs, overriding any `exclude`'s set

no clue how to solve it

**Comment by amencarini** [comment]
Doing some cleanup of my issues...
