### ISSUE TITLE
Set :include_default_locale to true ignored

### ISSUE THREAD

**Issue by phlegx** [svenfuchs/routing-filter#57]
Hi!

I use gem version ```0.5.0``` and rails ```4.3.2```. If I set ```RoutingFilter::Locale.include_default_locale = true``` (in ```config/initializers/routing_filter.rb```) in the response header the url is without locale. Any idea how to include locale in the response header url?

The request has ```localhost:3000/en/test``` but if I print out ```request.url``` in the controller action, I get ```localhost:3000/test```! Why?

**Comment by phlegx** [comment]
This commit solves the problem and works for me: https://github.com/gauda/routing-filter/commit/6595ae1e3fdaea38476bf92a01fb8ab7ad5d43de 

@svenfuchs please add this to the code. Thx.

**Comment by simi** [comment]
@phlegx hello. This is merged into master. Can you try master and close this issue if that's working for you now! I will release new version if you confirm this. Thanks!

**Comment by phlegx** [comment]
@simi I use this https://github.com/gauda/routing-filter/commit/6595ae1e3fdaea38476bf92a01fb8ab7ad5d43de and it is the same as your commit. So, it works. Please release.

**Comment by simi** [comment]
It's [out](https://rubygems.org/gems/routing-filter/versions/0.5.1) my lord!

**Comment by phlegx** [comment]
Yupppiiii :+1:
