### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by bricesanchez** [svenfuchs/routing-filter#61]
Hello, 

Rails 5 is around the corner and this PR is already merged : https://github.com/svenfuchs/routing-filter/pull/60

Could you release a new gem version ?

**Comment by simi** [comment]
sure, let me prepare that :panda_face:

**Comment by bricesanchez** [comment]
Thanks @simi!

**Comment by simi** [comment]
@bricesanchez can you try https://github.com/svenfuchs/routing-filter/compare/rails5-warnings?expand=1 ? Does that work for you? I also solved few warnings. CI is ok for Rails 5.0.0.rc1 and latest Rails 4.2.

**Comment by kevin-jj** [comment]
@bricesanchez @simi  any updates?

**Comment by bricesanchez** [comment]
@kevin-jj i don't have any updates yet but i will come back soon on the project i want to update to rails 5.

**Comment by simi** [comment]
Sorry I'm out for this weekend. I will release on Monday. Sorry for delay!

Dne pátek 15. července 2016 Brice Sanchez <notifications@github.com>
napsal(a):
> @kevin-jj i don't have any updates yet but i will come back soon on the
project i want to update to rails 5.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/HF6GVfrqLyDagimpepyyHfMBzGC1K_oxioGucXoe2MTJ8K_G5nl2We4QskgN8X01Or30kdSvDKsBj_MbWLnH1HtmTK8niM_uzdQnCHcNBlh1QhBYcCFC-yUMmQ4Xm-2X98V_GvZtjGNrBG37gFNABopVgHHOCw=s0-d-e1-ft#https://github.com/notifications/beacon/AAL1kBpo3McHGXnZVNdJbDGx_bIr6VwTks5qV4dFgaJpZM4Ibpzr.gif
>

**Comment by simi** [comment]
:balloon:  @bricesanchez @kevin-jj 0.6 released. :tada:

**Comment by bricesanchez** [comment]
Thanks @simi!
