### ISSUE TITLE
Please release new gem version

### ISSUE THREAD

**Issue by johnnyshields** [svenfuchs/routing-filter#78]
Rails 6.1 support is not released yet, please cut a gem release. @simi

**Comment by simi** [comment]
:partying_face: https://rubygems.org/gems/routing-filter/versions/0.7.0

**Comment by johnnyshields** [comment]
@simi you da man!! Thank you 🎉

**Comment by johnnyshields** [comment]
Don't forget to tag in GH :)

**Comment by simi** [comment]
ahh, done
